name: Unit tests for Basic Class

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: python -m pytest

      
